### ISSUE TITLE
Remember Current User on refresh

### ISSUE THREAD

**Issue by costomato** [Suyious/purrr.frontend#10]
Fix onboarding issue: Make sure refreshing the website does not start the onboarding process again. Instead, put a gear icon for settings, from where the username and Name can be set/changed.

**Comment by HarshNarayanJha** [comment]
I think we can save user info in browser cookies/local storage. I will look into it

**Comment by costomato** [comment]
yep, that's what we were talking about. 

Ok, please look into the new contribution rules later. We will put them in Readme (not done yet).

**Comment by HarshNarayanJha** [comment]
Okay I'm done, and it's working with the backend (no changes required there). I will wait for the rules before committing/pushing anything
