### ISSUE TITLE
Save Username for Current Browser Session only

### ISSUE THREAD

**Issue by HarshNarayanJha** [Suyious/purrr.frontend#35]
Currently, the username is being saved to the `localStorage`, which persists sessions (i.e. reopening the browser). The idea was to save that only for this session, and don't load the username in the next session, and start from scratch.

              I forgot to mention earlier that the idea was to limit username persistence to the current browser session only. Once we quit and reopen the browser, the onboarding data should reset.

_Originally posted by @costomato in https://github.com/Suyious/purrr.frontend/issues/4#issuecomment-2365209701_

**Comment by HarshNarayanJha** [comment]
Assign me

**Comment by Suyious** [comment]
I think localStorage is good right now. I'm not looking for this change currently.

**Comment by HarshNarayanJha** [comment]
Really? That's fine then!
