### ISSUE TITLE
Bug: Read message implementation is incomplete

### ISSUE THREAD

**Issue by HarshNarayanJha** [Suyious/purrr.frontend#37]
The frontend just marks a message as read if the chat window is scrolled enough to the bottom.

We should use something like `window.onblur` and `window.onfocus` or `document.onvisibilitychange` events to actually mark the message as read (or the [UserActivation](https://developer.mozilla.org/en-US/docs/Web/API/UserActivation) API)
Along with the scrollBottom implementation.

**Comment by Suyious** [comment]
I am already working on this. It's not only imcompletely implemented not incorrectly implemented since the current functionality is also needed. However, you can work on it. Just know that I am also working on it.

**Comment by Suyious** [comment]
Also closes #36
